name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v3

      # 2. Устанавливаем Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Устанавливаем зависимости MkDocs
      - name: Install dependencies
        run: pip install --upgrade pip mkdocs mkdocs-material

      # 4. Собираем сайт
      - name: Build MkDocs site
        run: mkdocs build

      # 5. Деплой на GitHub Pages через Action
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GHTOKEN2 }}  # используем твой новый секрет
          publish_dir: ./site                      # папка со сгенерированным сайтом

